### ISSUE TITLE
Failed to list brightness devices - EnumerationMismatch (Windows)

### ISSUE THREAD

**Issue by mruac** [jacob-pro/solar-screen-brightness#10]
Heyo - interesting GUI, the transition feature is definitely a plus, if I can get this working.

It's not able to detect my monitor - ClickMonitorDDC tells me that I have a VC279. It's an ASUS brand

![image](https://user-images.githubusercontent.com/19784752/137812722-1031792d-d9b5-4c01-a40e-114da6ebf1ef.png)

I'm using the pre-built release [0.1.0](https://github.com/jacob-pro/solar-screen-brightness/releases/tag/0.1.0) for Windows.

Edition	Windows 10 Home
Version	20H2
Installed on	‎19/‎11/‎2020
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by jacob-pro** [comment]
@mruac Thank you for the detailed explanation! I was able to get a fix merged upstream

Please can you try the latest release?
https://github.com/jacob-pro/solar-screen-brightness/releases/tag/0.1.2

It is working fine for me now when having only one display enabled in windows settings - hopefully it will work for you too

**Comment by mruac** [comment]
Heyo - thanks for providing a fix! SSB can now adjust my external monitor just fine. Now it's a matter of getting it to work for real this time...
I'll set up a separate issue explaining it.
