### ISSUE TITLE
Installer does nothing on Windows 10 

### ISSUE THREAD

**Issue by eddie-LA** [jacob-pro/solar-screen-brightness#12]
Hello,

I was looking for an app like this for a long time. Unfortunately, the setup just quits after pressing Enter to install. No changes made to the system, the app is nowhere to be found in %APPDATA% or Program Files. Elevation privileges don't make a difference.

**Comment by jacob-pro** [comment]
Please can you try running the installer from the command line? You should be able to see the log output then.

**Comment by jacob-pro** [comment]
I have created a new release that will display the error in a popup in case the installer crashes

**Comment by eddie-LA** [comment]
Huh... This one installed just fine. I ran the other one previously but it didn't do anything yesterday. This one I ran once, displayed "Success", then clicked "Launch app" - all good. App is located in Roaming.
