### ISSUE TITLE
Console window is not hidden when using Windows Terminal as default host (Windows 11)

### ISSUE THREAD

**Issue by xPaw** [jacob-pro/solar-screen-brightness#22]
When using this option:
![image](https://user-images.githubusercontent.com/613331/191476199-0e3113a2-5bdf-4b86-8c08-6e94cc1c519e.png)

The console window is visible when SSB is running. Closing it closes SSB.

**Comment by jacob-pro** [comment]
that sounds annoying 😆 

I'm planning to rewrite the whole UI in QT when I have time, this project started out as an experimental / uni project and needs an overhaul lol

**Comment by jacob-pro** [comment]
One work around you could use is once you are setup you can launch the app in headless mode, and there will be no UI shown at all

```bash
./solar-screen-brightness.exe headless
```

**Comment by xPaw** [comment]
I've worked around it by using RunHiddenConsole which I had lying around.

**Comment by claell** [comment]
I have the same issue, but good to see there is already an issue open about it.

I am not sure, but it seems like this is the only tool around that actually supports scheduling brightness changes automatically on Windows? So I'd really benefit from a quick fix :)

Else, I am also very interested to hear alternatives for now.

**Comment by caesay** [comment]
Indeed, this is a simple fix, it just needs to be recompiled with subsystem:windows instead of subsystem:console. Thanks for the RunHiddenConsole suggestion in the mean time.

**Comment by cristipopescu1** [comment]
I confirm that changing the default terminal to "windows host" fixes this

**Comment by jacob-pro** [comment]
Version 2.0 has a new UI that no longer relies on a console window - so this should no longer be an issue

**Comment by claell** [comment]
Additionally, I noticed that some Windows update apparently fixed the bug for me with the old version as well.

**Comment by claell** [comment]
For some reason, the console window returned back again, after not appearing, before.

But the new GUI version works flawlessly, I just updated!
