### ISSUE TITLE
Failed to persist temporary file: invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by legop3** [jacob-pro/solar-screen-brightness#36]
When trying to use SSB on lubuntu 22.04, attempting to save to the configuration file results in a pop-up window and a log entry that states `Failed to persist temporary file: invalid cross-device link (os error 18)`. The config file is never created.

ssb-cli, when executed, exits immediately saying `Config file does not exist`.

SSB was installed using the Ubuntu install script.

**Comment by jacob-pro** [comment]
The default config file is loaded and saved to this path:

https://github.com/jacob-pro/solar-screen-brightness/blob/bdb7a87326ac37f3ee24bd6cd45aeb8786024600/src/common.rs#L24-L27

which should resolve to something like `/home/$USER/.config`, see https://docs.rs/dirs/5.0.1/dirs/fn.config_local_dir.html

When saving config via the UI it is written to a tempfile first to prevent corruption if it exited whilst writing:

https://github.com/jacob-pro/solar-screen-brightness/blob/bdb7a87326ac37f3ee24bd6cd45aeb8786024600/src/config.rs#L101-L106

It must be that your system's temp directory and your home directory are on a different filesystem and therefore unable to replace.

As a workaround you can manually create the config file yourself first, if you are using `ssb-cli` you can use an argument to set the path to it:
https://github.com/jacob-pro/solar-screen-brightness/issues/25#issuecomment-1885951106

```
{
  "brightness_day": 70,
  "brightness_night": 40,
  "transition_mins": 40,
  "location": {
    "latitude": 0,
    "longitude": 0
  },
  "overrides": []
}
```

I will try and fix the saving issue shortly.

**Comment by jacob-pro** [comment]
This should be fixed in https://github.com/jacob-pro/solar-screen-brightness/releases/tag/2.3.1
Please let me know if this is working for you now @legop3  ?

**Comment by legop3** [comment]
Hi, sorry I never caught your first response. I will let you know whether this works or not. To get it working, I installed it on a different computer to create the config file, then moved it over. Good on you for making it easy to edit manually!
